---
resources:
- name: isv-tech-docs
  type: git
  source:
    uri: git@github.com:cf-platform-eng/isv-tech-docs.git
    private_key: ((isv-tech-docs-deploy-key-ci))
    branch: master

- name: isv-tech-hub-gh-pages
  type: git
  source:
    uri: git@github.com:cf-platform-eng/isv-tech-hub.git
    private_key: ((isv-tech-hub-deploy-key-ci))
    branch: gh-pages


jobs:
  - name: deploy-isv-tech-docs
    build_log_retention:
        builds: 10
    plan:
    - in_parallel:
      - get: isv-tech-hub-gh-pages
      - get: isv-tech-docs
        trigger: true

    - do:
      - task: build-mkdocs
        input_mapping:
          mkdocs-in: isv-tech-docs
        config:
          inputs:
            - name: mkdocs-in
          outputs:
            - name: mkdocs-site-out
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: dherbrich/mkdocs-material-awesome-pages
              tag: 0.1.0
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                 mkdocs build -f "${PWD}/mkdocs-in/mkdocs.yml" -d "${PWD}/mkdocs-site-out"

      - task: deploy-isv-tech-hub-ghpages
        input_mapping:
          mkdocs-site-in: mkdocs-site-out
        config:
          inputs:
            - name: mkdocs-site-in
            - name: isv-tech-hub-gh-pages
          outputs:
            - name: isv-tech-hub-gh-pages
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: alpine/git
              tag: latest
          run:
            path: /bin/sh
            args:
            - -exc
            - |
              function check_in() {
                git add .
                git config --global user.email cf-platform-eng+ci@pivotal.io
                git config --global user.name ISVTechHubCI
                git commit -am"$1" || true ;
              }
                ls -alh isv-tech-hub-gh-pages
                cp -a ./mkdocs-site-in/. ./isv-tech-hub-gh-pages

              cd ./isv-tech-hub-gh-pages
                ls -al
                git status
                check_in ":whale: Update ISV Tech Hub Docs"
                git status
              
        on_success:
          put: isv-tech-hub-gh-pages
          params: {rebase: true, force: true, repository: isv-tech-hub-gh-pages }
